### PR TITLE
build fixes for zig dev 0.14.0-dev.1820+ea527f7a8

### PR DESCRIPTION
**Pull request by nurpax**
Catching up with some latest Zig compiler & build system changes.

Not sure of the include dir change is correct but it's working at least when running `zig build test` and `zig build run-example-interpreter`

for #104

### CODE REVIEW

**Comment by nurpax** [comment]
CI won't pass with this change since CI uses 0.13 and this fixes 0.14 dev.

**Comment by natecraddock** [comment]
Thank you for working on this! You are welcome to update the ci in the PR if you want.

I'm unsure of if I want to merge this into main, or if I want this in a dev branch of some kind. I'll give that some thought before merging

**Comment by nurpax** [comment]
Yeah, better think it through where these devel versions should live.  One alternative would be to keep main as the "latest possible zig version" and then a branch per real zig versioned release.  IMO this model generally makes it a little easier to know where to work on new stuff as it'll always be main.

**Comment by nurpax** [comment]
> You are welcome to update the ci in the PR if you want.

Why didn't I think of that. 😄 I force-pushed an updated commit and it's passing now.

**Comment by natecraddock** [comment]
Yeah I agree keeping `main` as following Zig master is a good idea. I'll branch off the commit before this one to make a Zig 0.13.0 branch as needed

**Pull request merged**
