### PR TITLE
Parsing memory fixes

### LINKED ISSUE #62: Proposed fixes to memory management issues with parsing
Here's an issue I've realized we have with the current parsing setup

Currently, when parsing a struct with lots of different arrays and pointers from a lua table, freeing that memory could get quite complex. The `toAny` and `autoCall` functions should be modified to return a `ziglua.Parsed` struct which contains an arena allocator which can be used to free the memory easily. 

We can also add a `toAnyLeaky` and `autoCallLeaky` that leaves memory deallocation to be done manually as happens in the current implementation (as a toAny call may not necessarily require a memory allocation).

### PR DESCRIPTION
**Pull request by VisenDev**
Closes #62

### CODE REVIEW

**Comment by VisenDev** [comment]
@natecraddock After thinking about this some more, an alternative way of managing this memory could be to have a specific `toAnyScalar` that just returns basic types and thus has no need for memory allocation, and having a `toAny` that can allocate memory for slices that returns a `ziglua.Parsed(T)`

Alternative names could be `toAny` and `toAnyAlloc`. `toAny` will warn you if you give a type that needs memory allocation to parse at compile time, in which case you can use `toAnyAlloc`

**Comment by VisenDev** [comment]
Actually thinking about it more I think I like using a `toAny` and a `toAnyAlloc` instead of my current approach. It seems to make a lot more sense and follows zig's library memory allocator passing convention better. I am going to rework some things

**Comment by VisenDev** [comment]
I think the checks are failing because of some sort of network error, it doesn't seem to be related to the code

**Comment by natecraddock** [comment]
I'm going to go ahead and merge this as-is. There are some small things I might want to tweak later, but that polish can come before the 0.3.0 release of ziglua (that I want to make shortly after Zig 0.12.0)

**Pull request merged**
